language: python
python:
  - 2.7
  - 3.5
install:
    - "pip install -r requirements.txt"
    - pip install coveralls    
script:
    - coverage run --source=team-sync test
after_success:
    coveralls